classPath:
- MinimalReproducibleExample-0069/analyzed-programs
appClassPath: []
mainClass: Main
inputClasses: []
outputDir: MinimalReproducibleExample-0069/output
worldBuilderClass: pascal.taie.frontend.java.JavaWorldBuilder
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
analyses:
  pta:
    cs: ci
    implicit-entries: true
    distinguish-string-constants: null
    reflection-inference: solar
    taint-config: MinimalReproducibleExample-0069/configs/taint-config.yml
keepResult:
- $KEEP-ALL
